disabled_rules:
  - file_length
  - function_body_length
  - line_length
  - nesting
  - todo
  - trailing_whitespace
  - type_body_length
  - vertical_whitespace

excluded:
  - Sources/Tutti/UIKit/Hints/CalloutView.swift

included:
  - Sources
  - Tests

identifier_name:
  excluded:
    - id
    - ok
    - up
    - vc
    - x
    - y
